/* 口試模擬題庫 · C10 v126
   依「115 年導遊人員及領隊人員評量測驗簡章」外語導遊口試:每人約 10–12 分鐘,
   題目包括「自我介紹」「本國文化與國情」「風景、節慶與美食」三大部分(p = 1 / 2 / 3)。
   en:英語題目 + 參考回答(sample)+ 關鍵字(kw:[英文, 中文]);內容為練習用自編範例,非官方題目。
   jp:日語題目;參考回答與關鍵字沿用 oral_jp.js 的口試主題範例(ref = ORALJP.topics 的索引),
       或直接附在題目上(ja 日語句子、jz 對應中文、jk 關鍵字 [日語, 讀音, 中文])。
   變更履歷:
     v129 (2026-10-05) 題目擴充:英語 16 → 27、日語 15 → 26(客家文化、茶文化、旅遊季節、綠島、溫泉禮儀、墾丁、台南、平溪天燈、珍珠奶茶、澎湖等)
     v126 初版 */
const ORALMOCK = {
  parts: { 1: '自我介紹', 2: '本國文化與國情', 3: '風景、節慶與美食' },
  en: [
    { p: 1, q: 'Please introduce yourself and tell us why you want to be a tour guide.', zh: '請自我介紹,並說明想當導遊的原因。',
      sample: ['Good morning. My name is Lin, and I am from Taichung.', 'I majored in English at university and have worked in hospitality for three years.', 'I love meeting people from different countries and sharing stories about Taiwan.', 'I hope to become a tour guide who makes every visitor feel welcome and safe.'],
      kw: [['major in', '主修'], ['hospitality', '接待服務業'], ['be passionate about', '熱愛'], ['make visitors feel welcome', '讓旅客賓至如歸']] },
    { p: 2, q: 'Could you give a brief introduction to Taiwan?', zh: '請簡單介紹台灣。',
      sample: ['Taiwan is an island in East Asia with a population of about 23 million.', 'It is known for its high mountains, hot springs and beautiful coastline.', 'Taipei is the capital, and Mandarin and Taiwanese are widely spoken.', 'Visitors love Taiwan for its friendly people, convenient transportation and delicious food.'],
      kw: [['population', '人口'], ['mountainous', '多山的'], ['coastline', '海岸線'], ['convenient', '方便的']] },
    { p: 2, q: "Tell us about Taiwan's indigenous peoples.", zh: '請介紹台灣的原住民族。',
      sample: ['Taiwan has 16 officially recognized indigenous peoples.', 'The Amis are the largest group, living mainly on the east coast.', 'Each group has its own language, festivals and traditional clothing.', 'Visitors can learn about their culture at harvest festivals and cultural parks.'],
      kw: [['indigenous peoples', '原住民族'], ['officially recognized', '官方認定'], ['Amis', '阿美族'], ['harvest festival', '豐年祭']] },
    { p: 2, q: 'How can visitors travel around Taiwan?', zh: '旅客在台灣可以怎麼移動?',
      sample: ["Taiwan's High Speed Rail connects Taipei and Kaohsiung in about 90 minutes.", 'In the cities, the MRT is fast, clean and easy to use.', 'An EasyCard can be used on the MRT, on buses and even in convenience stores.', 'For the east coast, trains and tour buses are good choices.'],
      kw: [['High Speed Rail', '高鐵'], ['MRT', '捷運'], ['EasyCard', '悠遊卡'], ['convenience store', '便利商店']] },
    { p: 2, q: 'Tell us about religion and temple culture in Taiwan.', zh: '請介紹台灣的宗教與廟宇文化。',
      sample: ['Many people in Taiwan follow a mix of Buddhism, Taoism and folk beliefs.', 'Temples are community centers, and Mazu, the goddess of the sea, is widely worshipped.', 'During the Mazu pilgrimage, thousands of followers walk for days with the goddess.', 'When visiting a temple, please be quiet and respectful, and ask before taking photos.'],
      kw: [['temple', '廟宇'], ['folk beliefs', '民間信仰'], ['Mazu pilgrimage', '媽祖遶境'], ['incense', '香']] },
    { p: 3, q: 'Please introduce Taipei 101 to a group of visitors.', zh: '請向旅客介紹台北 101。',
      sample: ['Taipei 101 is a 508-meter skyscraper in the Xinyi District of Taipei.', 'It was the tallest building in the world from 2004 to 2010.', 'Its design looks like a stalk of bamboo, a symbol of growth.', 'Inside, a huge tuned mass damper keeps the tower steady during typhoons and earthquakes.'],
      kw: [['skyscraper', '摩天大樓'], ['observatory', '觀景台'], ['tuned mass damper', '風阻尼器'], ["New Year's Eve fireworks", '跨年煙火']] },
    { p: 3, q: 'What would you tell visitors about the National Palace Museum?', zh: '你會怎麼向旅客介紹國立故宮博物院?',
      sample: ["The National Palace Museum in Taipei houses one of the world's largest collections of Chinese art.", 'Its collection has nearly 700,000 pieces spanning thousands of years.', 'The most famous items include the Jadeite Cabbage and the Meat-shaped Stone.', 'I suggest visiting early in the morning to avoid the crowds.'],
      kw: [['collection', '典藏'], ['artifact', '文物'], ['Jadeite Cabbage', '翠玉白菜'], ['Meat-shaped Stone', '肉形石']] },
    { p: 3, q: 'Please introduce Jiufen.', zh: '請介紹九份。',
      sample: ['Jiufen is a mountain town in New Taipei City that grew rich from gold mining.', 'Its narrow old streets are full of teahouses, red lanterns and snack shops.', 'From the town you can enjoy a great view of the sea and the mountains.', 'Many visitors love its nostalgic atmosphere, especially in the evening when the lanterns are lit.'],
      kw: [['gold mining', '採金'], ['old street', '老街'], ['teahouse', '茶樓'], ['nostalgic', '懷舊的']] },
    { p: 3, q: 'Introduce Sun Moon Lake to your tour group.', zh: '請向團員介紹日月潭。',
      sample: ['Sun Moon Lake is the largest lake in Taiwan, located in Nantou County.', 'Its name comes from its shape: one part looks like the sun and the other like the moon.', 'Visitors can take a boat ride, ride a bike along the lake or take the cable car.', "It is also home to the Thao people, one of Taiwan's indigenous groups."],
      kw: [['lake', '湖泊'], ['cable car', '纜車'], ['cycling path', '自行車道'], ['Thao people', '邵族']] },
    { p: 3, q: 'What can visitors see at Alishan?', zh: '旅客在阿里山可以看到什麼?',
      sample: ['Alishan is a famous mountain area in Chiayi County.', 'It is well known for the sunrise, the sea of clouds and the giant sacred trees.', 'Visitors can ride the Alishan Forest Railway, a famous mountain railway.', 'In spring, the cherry blossoms make Alishan even more beautiful.'],
      kw: [['sunrise', '日出'], ['sea of clouds', '雲海'], ['sacred tree', '神木'], ['forest railway', '森林鐵路']] },
    { p: 3, q: 'Please introduce Taroko National Park.', zh: '請介紹太魯閣國家公園。',
      sample: ['Taroko National Park is in Hualien on the east coast of Taiwan.', 'The Taroko Gorge was cut by the Liwu River through marble cliffs.', 'Popular spots include the Swallow Grotto and the Eternal Spring Shrine.', 'Please check the trail conditions before visiting, because some trails may close after earthquakes or heavy rain.'],
      kw: [['gorge', '峽谷'], ['marble', '大理石'], ['Swallow Grotto', '燕子口'], ['Eternal Spring Shrine', '長春祠']] },
    { p: 3, q: 'Why are night markets so popular in Taiwan?', zh: '為什麼夜市在台灣這麼受歡迎?',
      sample: ['Night markets are an important part of daily life in Taiwan.', 'Shilin Night Market in Taipei is one of the most famous.', 'You can try local snacks like stinky tofu, oyster omelets and bubble tea.', "There are also games and inexpensive clothes, so it's fun for everyone."],
      kw: [['street food', '街頭小吃'], ['stinky tofu', '臭豆腐'], ['oyster omelet', '蚵仔煎'], ['bargain', '殺價']] },
    { p: 3, q: 'Recommend some Taiwanese dishes to foreign visitors.', zh: '請向外國旅客推薦台灣料理。',
      sample: ["Beef noodle soup is one of Taiwan's most famous dishes.", 'Xiaolongbao, or soup dumplings, are very popular with visitors.', 'Braised pork rice is a simple but delicious local favorite.', 'For dessert, try mango shaved ice or a cup of bubble milk tea.'],
      kw: [['beef noodle soup', '牛肉麵'], ['soup dumplings', '小籠包'], ['braised pork rice', '滷肉飯'], ['shaved ice', '剉冰']] },
    { p: 3, q: 'Please introduce a traditional festival in Taiwan.', zh: '請介紹一個台灣的傳統節慶。',
      sample: ['The Lantern Festival is on the 15th day of the first lunar month.', 'In Pingxi, people write their wishes on sky lanterns and release them into the night sky.', 'In Yanshui, people enjoy the exciting beehive fireworks.', 'Other important festivals include the Dragon Boat Festival and the Mid-Autumn Festival.'],
      kw: [['lunar calendar', '農曆'], ['sky lantern', '天燈'], ['beehive fireworks', '鹽水蜂炮'], ['Dragon Boat Festival', '端午節']] },
    { p: 3, q: 'Introduce Beitou Hot Springs to visitors.', zh: '請向旅客介紹北投溫泉。',
      sample: ['Beitou is a hot spring area in northern Taipei that is easy to reach by MRT.', 'Its hot spring culture began during the Japanese colonial period.', 'Visitors can see the Thermal Valley and the Beitou Hot Spring Museum.', 'Remember to wash before entering a public bath and to drink enough water.'],
      kw: [['hot spring', '溫泉'], ['Thermal Valley', '地熱谷'], ['colonial period', '殖民時期'], ['public bath', '公共浴池']] },
    { p: 3, q: 'What souvenirs would you recommend from Taiwan?', zh: '你會推薦哪些台灣伴手禮?',
      sample: ['Pineapple cakes are the most popular souvenir from Taiwan.', 'High-mountain oolong tea is another great choice.', 'Some visitors like nougat candy or dried mango.', 'You can buy them at bakeries, tea shops or the airport.'],
      kw: [['pineapple cake', '鳳梨酥'], ['oolong tea', '烏龍茶'], ['nougat', '牛軋糖'], ['dried mango', '芒果乾']] },
    { p: 1, q: 'Please introduce yourself and tell us what makes a good tour guide.', zh: '請自我介紹,並說明你認為好導遊應具備什麼條件。',
      sample: ['Hello, my name is Chen. I was born and raised in Tainan.', 'I studied tourism in college and have volunteered as a guide at local temples.', 'I believe a good tour guide should be knowledgeable, patient, and always put safety first.', 'I would like to show visitors the real Taiwan, from its history to its friendly people.'],
      kw: [['born and raised', '土生土長'], ['volunteer', '擔任志工'], ['knowledgeable', '知識豐富的'], ['put safety first', '安全第一']] },
    { p: 2, q: 'Tell us about Hakka culture in Taiwan.', zh: '請介紹台灣的客家文化。',
      sample: ["The Hakka people make up about one-fifth of Taiwan's population.", 'Many Hakka communities are in Taoyuan, Hsinchu, Miaoli, and Meinong in Kaohsiung.', 'Hakka culture is known for hard work and thrift, and for dishes such as Hakka stir-fry and lei cha, or pounded tea.', 'Every spring, the Hakka Tung Blossom Festival celebrates the white tung flowers in the hills.'],
      kw: [['make up', '占(比例)'], ['thrift', '節儉'], ['pounded tea (lei cha)', '擂茶'], ['tung blossom', '油桐花']] },
    { p: 2, q: 'Tell us about Taiwanese tea culture.', zh: '請介紹台灣的茶文化。',
      sample: ['Taiwan is famous for oolong tea, which is partially fermented.', 'High-mountain oolong from Alishan and Lishan has a fresh, floral aroma.', 'Oriental Beauty tea from Hsinchu and Miaoli gets its honey-like flavor from tiny insects that bite the leaves.', 'Visitors can enjoy tea at the teahouses of Maokong in Taipei while looking at the night view.'],
      kw: [['oolong tea', '烏龍茶'], ['partially fermented', '部分發酵'], ['aroma', '香氣'], ['teahouse', '茶藝館']] },
    { p: 2, q: 'When is the best time to visit Taiwan, and why?', zh: '什麼時候最適合來台灣旅遊?為什麼?',
      sample: ['Northern Taiwan has a subtropical climate, and the south has a tropical climate.', 'Spring and autumn are the most comfortable seasons, with mild temperatures and less rain.', 'Summer is hot and humid, and typhoons mostly come between July and September.', 'In winter, the north can be cool and rainy, while the south stays warm and sunny.'],
      kw: [['subtropical', '亞熱帶的'], ['humid', '潮濕的'], ['typhoon', '颱風'], ['mild', '溫和的']] },
    { p: 3, q: 'Please introduce Green Island.', zh: '請介紹綠島。',
      sample: ['Green Island is a small volcanic island off the coast of Taitung.', 'It is famous for Zhaori Hot Spring, one of the few seawater hot springs in the world.', 'Visitors can go snorkeling to see coral reefs and colorful fish.', 'The White Terror Memorial Park on the island helps visitors learn about human rights in Taiwan.'],
      kw: [['volcanic island', '火山島'], ['seawater hot spring', '海底溫泉'], ['snorkeling', '浮潛'], ['human rights', '人權']] },
    { p: 3, q: 'What etiquette should visitors follow at a public hot spring?', zh: '在公共溫泉應注意哪些禮儀?',
      sample: ['First, rinse your body before you get into the pool.', 'Follow the rules of each place: many public pools require swimsuits and caps, while gender-separated baths are usually used without clothes.', 'Tie up long hair and keep your towel out of the water.', 'Soak for about ten to fifteen minutes at a time, drink some water, and do not soak after drinking alcohol.'],
      kw: [['rinse', '沖洗'], ['gender-separated', '男女分開的'], ['soak', '浸泡'], ['etiquette', '禮儀']] },
    { p: 3, q: 'Please introduce Kenting National Park.', zh: '請介紹墾丁國家公園。',
      sample: ["Kenting is Taiwan's first and southernmost national park, at the tip of the Hengchun Peninsula.", 'It has a tropical climate, sandy beaches, and raised coral reefs.', 'Visitors can see the Eluanbi Lighthouse and enjoy water sports in summer.', 'Every October, flocks of gray-faced buzzards fly over Kenting on their way south.'],
      kw: [['southernmost', '最南端的'], ['peninsula', '半島'], ['coral reef', '珊瑚礁'], ['lighthouse', '燈塔']] },
    { p: 3, q: 'Please introduce Tainan.', zh: '請介紹台南。',
      sample: ["Tainan is Taiwan's oldest city and was its political center for more than two hundred years.", 'Visitors can explore Fort Zeelandia, built by the Dutch in the 17th century, and Chihkan Tower.', 'Its Confucius Temple was the first one built in Taiwan.', 'Tainan is also a food paradise, famous for danzai noodles, milkfish soup, and beef soup.'],
      kw: [['political center', '政治中心'], ['fort', '城堡(要塞)'], ['Confucius Temple', '孔廟'], ['food paradise', '美食天堂']] },
    { p: 3, q: 'Please introduce the Pingxi Sky Lantern Festival.', zh: '請介紹平溪天燈節。',
      sample: ['The Pingxi Sky Lantern Festival is held around the Lantern Festival, on the 15th day of the first lunar month.', 'People write their wishes on paper lanterns and release them into the night sky.', 'Pingxi is in the mountains of New Taipei and can be reached by the Pingxi railway line.', 'Seeing thousands of lanterns rise together is an unforgettable experience.'],
      kw: [['sky lantern', '天燈'], ['make a wish', '許願'], ['lunar calendar', '農曆'], ['release', '施放']] },
    { p: 3, q: 'Please introduce bubble tea.', zh: '請介紹珍珠奶茶。',
      sample: ['Bubble tea, or pearl milk tea, was created in Taiwan in the 1980s.', 'It is milk tea with chewy tapioca pearls made from cassava starch.', 'You can choose the sugar level and the amount of ice.', 'Today it is popular all over the world and has become a symbol of Taiwan.'],
      kw: [['tapioca pearls', '粉圓(珍珠)'], ['chewy', '有嚼勁的'], ['sugar level', '甜度'], ['symbol', '象徵']] },
    { p: 3, q: 'Please introduce Penghu.', zh: '請介紹澎湖。',
      sample: ['Penghu is an archipelago of about ninety islands in the Taiwan Strait.', 'It is famous for basalt columns and traditional stone fish traps, such as the Twin Hearts Stone Weir on Qimei.', 'From spring to summer, the Penghu International Fireworks Festival attracts many visitors.', 'Winter is very windy, so the best time to visit is from April to September.'],
      kw: [['archipelago', '群島'], ['basalt', '玄武岩'], ['stone fish weir', '石滬'], ['fireworks festival', '花火節']] }
  ],
  jp: [
    { p: 1, q: '自己紹介をしてください。ガイドを目指す理由も教えてください。', zh: '請自我介紹,並說明想當導遊的原因。', ref: 0 },
    { p: 2, q: '台湾について簡単に紹介してください。', zh: '請簡單介紹台灣。', ref: 1 },
    { p: 2, q: '台湾の原住民族について説明してください。', zh: '請介紹台灣的原住民族。', ref: 12 },
    { p: 2, q: '台湾国内の移動手段を教えてください。', zh: '請介紹在台灣移動的交通方式。', ref: 13 },
    { p: 3, q: '台北101を日本のお客様に紹介してください。', zh: '請向日本旅客介紹台北 101。', ref: 2 },
    { p: 3, q: '国立故宮博物院の見どころを教えてください。', zh: '請介紹國立故宮博物院的看點。', ref: 3 },
    { p: 3, q: '九份を紹介してください。', zh: '請介紹九份。', ref: 4 },
    { p: 3, q: '日月潭の魅力を説明してください。', zh: '請說明日月潭的魅力。', ref: 5 },
    { p: 3, q: '阿里山ではどんな景色が楽しめますか。', zh: '在阿里山可以欣賞到什麼景色?', ref: 6 },
    { p: 3, q: '太魯閣国家公園を紹介してください。', zh: '請介紹太魯閣國家公園。', ref: 7 },
    { p: 3, q: '台湾の夜市について紹介してください。', zh: '請介紹台灣的夜市。', ref: 8 },
    { p: 3, q: '日本のお客様におすすめの台湾料理を紹介してください。', zh: '請向日本旅客推薦台灣料理。', ref: 9 },
    { p: 3, q: '台湾の伝統的なお祭りを一つ紹介してください。', zh: '請介紹一個台灣的傳統節慶。', ref: 10 },
    { p: 3, q: '北投温泉を紹介してください。', zh: '請介紹北投溫泉。', ref: 11 },
    { p: 3, q: '台湾のおすすめのお土産を教えてください。', zh: '請推薦台灣的伴手禮。', ref: 14 },
    { p: 1, q: '自己紹介をしてください。また、良いガイドに必要なことは何だと思いますか。', zh: '請自我介紹,並說明你認為好導遊應具備什麼條件。',
      ja: ['はじめまして。陳と申します。台南で生まれ育ちました。', '大学で観光を学び、地元のお寺でボランティアガイドをしていました。', '良いガイドには豊富な知識と思いやり、そして何よりもお客様の安全を守る意識が大切だと思います。', '台湾の歴史や人々の温かさを、日本のお客様に伝えたいです。'],
      jz: ['初次見面,我姓陳,在台南土生土長。', '大學讀觀光,曾在當地廟宇擔任志工導覽。', '我認為好導遊需要豐富的知識和體貼,最重要的是守護旅客安全的意識。', '我想把台灣的歷史和人情味介紹給日本旅客。'],
      jk: [['生まれ育つ', 'うまれそだつ', '土生土長'], ['思いやり', 'おもいやり', '體貼'], ['安全', 'あんぜん', '安全'], ['温かさ', 'あたたかさ', '溫暖、人情味']] },
    { p: 2, q: '台湾の客家文化について紹介してください。', zh: '請介紹台灣的客家文化。',
      ja: ['客家の人々は台湾の人口の約5分の1を占めています。', '桃園、新竹、苗栗、そして高雄の美濃などに多く住んでいます。', '勤勉で倹約家だと言われ、客家小炒や擂茶などの料理が有名です。', '毎年春には、山に咲く白い油桐の花を楽しむ「客家桐花祭」が開かれます。'],
      jz: ['客家人約占台灣人口的五分之一。', '多居住在桃園、新竹、苗栗,以及高雄美濃等地。', '客家人以勤勞節儉著稱,客家小炒和擂茶等料理很有名。', '每年春天會舉辦「客家桐花祭」,欣賞山間盛開的白色油桐花。'],
      jk: [['客家', 'はっか', '客家'], ['勤勉', 'きんべん', '勤勞'], ['倹約', 'けんやく', '節儉'], ['油桐', 'あぶらぎり', '油桐']] },
    { p: 2, q: '台湾のお茶の文化について教えてください。', zh: '請介紹台灣的茶文化。',
      ja: ['台湾は烏龍茶で有名です。烏龍茶は半発酵のお茶です。', '阿里山や梨山の高山茶は、すっきりとした花のような香りが特徴です。', '新竹や苗栗の東方美人茶は、小さな虫が葉をかじることで、はちみつのような甘い香りになります。', '台北の猫空では、茶藝館でお茶を味わいながら夜景を楽しめます。'],
      jz: ['台灣以烏龍茶聞名,烏龍茶是半發酵茶。', '阿里山、梨山的高山茶,特色是清爽的花香。', '新竹、苗栗的東方美人茶,因小蟲叮咬茶葉而帶有蜂蜜般的甘甜香氣。', '在台北貓空,可以在茶藝館一邊品茶一邊欣賞夜景。'],
      jk: [['半発酵', 'はんはっこう', '半發酵'], ['香り', 'かおり', '香氣'], ['茶藝館', 'ちゃげいかん', '茶藝館'], ['味わう', 'あじわう', '品嚐']] },
    { p: 2, q: '台湾旅行のベストシーズンはいつですか。理由も教えてください。', zh: '什麼時候最適合來台灣旅遊?為什麼?',
      ja: ['台湾は北部が亜熱帯、南部が熱帯の気候です。', '春と秋は気温が穏やかで雨も少なく、一番過ごしやすい季節です。', '夏は蒸し暑く、7月から9月ごろには台風が来ることがあります。', '冬の北部は寒くて雨が多いですが、南部は暖かい日が続きます。'],
      jz: ['台灣北部屬亞熱帶、南部屬熱帶氣候。', '春秋兩季氣溫溫和、雨也少,是最舒適的季節。', '夏天悶熱,7 到 9 月左右可能有颱風。', '冬天北部又冷又多雨,南部則持續溫暖。'],
      jk: [['亜熱帯', 'あねったい', '亞熱帶'], ['穏やか', 'おだやか', '溫和'], ['蒸し暑い', 'むしあつい', '悶熱'], ['台風', 'たいふう', '颱風']] },
    { p: 3, q: '緑島を紹介してください。', zh: '請介紹綠島。',
      ja: ['緑島は台東の沖にある小さな火山島です。', '世界でも珍しい海底温泉「朝日温泉」が有名です。', 'シュノーケリングでサンゴ礁やカラフルな魚を見ることができます。', '白色テロの記念園区では、台湾の人権の歴史を学べます。'],
      jz: ['綠島是台東外海的小火山島。', '世界上少見的海底溫泉「朝日溫泉」很有名。', '可以浮潛欣賞珊瑚礁和色彩繽紛的魚。', '在白色恐怖紀念園區,可以了解台灣的人權歷史。'],
      jk: [['火山島', 'かざんとう', '火山島'], ['海底温泉', 'かいていおんせん', '海底溫泉'], ['サンゴ礁', 'さんごしょう', '珊瑚礁'], ['人権', 'じんけん', '人權']] },
    { p: 3, q: '台湾の公共温泉では、どんなマナーに気をつければいいですか。', zh: '在台灣的公共溫泉,應注意哪些禮儀?',
      ja: ['まず、湯船に入る前に体を洗いましょう。', '台湾の露天風呂は水着や水泳帽が必要な所が多いですが、男女別の大浴場は裸で入るのが一般的です。', '長い髪はまとめて、タオルはお湯に入れないでください。', '一回の入浴は10分から15分ぐらいにして、水分をとりましょう。お酒を飲んだ後の入浴は避けてください。'],
      jz: ['首先,進浴池前先洗淨身體。', '台灣的露天溫泉多半需要穿泳衣、戴泳帽;男女分開的大浴場一般是裸湯。', '長髮要綁起來,毛巾不要放進池裡。', '每次泡 10 到 15 分鐘左右並補充水分;喝酒後請避免泡湯。'],
      jk: [['湯船', 'ゆぶね', '浴池'], ['水着', 'みずぎ', '泳衣'], ['男女別', 'だんじょべつ', '男女分開'], ['水分', 'すいぶん', '水分']] },
    { p: 3, q: '墾丁国家公園を紹介してください。', zh: '請介紹墾丁國家公園。',
      ja: ['墾丁は台湾で最初にできた、最も南にある国家公園です。', '恒春半島の先端にあり、一年中暖かい熱帯の気候です。', '白い砂浜やサンゴ礁が美しく、鵝鑾鼻灯台も人気の観光スポットです。', '毎年10月には、渡り鳥のサシバが南へ向かう途中で墾丁を通ります。'],
      jz: ['墾丁是台灣最早成立、位置最南端的國家公園。', '位在恆春半島尖端,終年溫暖,屬熱帶氣候。', '白色沙灘和珊瑚礁很美,鵝鑾鼻燈塔也是熱門景點。', '每年 10 月,候鳥灰面鵟鷹南遷途中會飛經墾丁。'],
      jk: [['先端', 'せんたん', '尖端'], ['砂浜', 'すなはま', '沙灘'], ['灯台', 'とうだい', '燈塔'], ['渡り鳥', 'わたりどり', '候鳥']] },
    { p: 3, q: '台南を紹介してください。', zh: '請介紹台南。',
      ja: ['台南は台湾で最も古い都市で、二百年以上にわたって台湾の政治の中心でした。', '17世紀にオランダ人が築いた安平古堡や、赤崁楼などの史跡があります。', '台南の孔子廟は、台湾で最初に建てられた孔子廟です。', '担仔麺やサバヒーのスープ、牛肉スープなど、グルメの町としても有名です。'],
      jz: ['台南是台灣最古老的城市,兩百多年間都是台灣的政治中心。', '有 17 世紀荷蘭人興建的安平古堡、赤崁樓等古蹟。', '台南孔廟是台灣第一座孔廟。', '擔仔麵、虱目魚湯、牛肉湯等,也是有名的美食之都。'],
      jk: [['史跡', 'しせき', '古蹟'], ['築く', 'きずく', '興建'], ['孔子廟', 'こうしびょう', '孔廟'], ['サバヒー', '', '虱目魚']] },
    { p: 3, q: '平渓の天燈祭りを紹介してください。', zh: '請介紹平溪天燈節。',
      ja: ['平渓の天燈祭りは、旧暦1月15日の元宵節のころに開かれます。', '人々は紙のランタンに願い事を書いて、夜空に放ちます。', '平渓は新北市の山あいにあり、ローカル線の平渓線で行くことができます。', '何千ものランタンが一斉に空へ昇る様子は、一生忘れられない光景です。'],
      jz: ['平溪天燈節在農曆正月十五元宵節前後舉行。', '人們在紙燈籠上寫下願望,放上夜空。', '平溪位在新北市的山間,可搭地方支線平溪線前往。', '數千盞天燈同時升空的景象令人一生難忘。'],
      jk: [['旧暦', 'きゅうれき', '農曆'], ['願い事', 'ねがいごと', '願望'], ['放つ', 'はなつ', '施放'], ['一斉に', 'いっせいに', '同時']] },
    { p: 3, q: 'タピオカミルクティーについて紹介してください。', zh: '請介紹珍珠奶茶。',
      ja: ['タピオカミルクティーは、1980年代に台湾で生まれた飲み物です。', 'キャッサバのでんぷんで作った、もちもちのタピオカが入っています。', '甘さや氷の量を自分の好みで選べます。', '今では世界中で人気があり、台湾を代表する飲み物になりました。'],
      jz: ['珍珠奶茶是 1980 年代在台灣誕生的飲料。', '裡面有用樹薯澱粉做成、Q 彈的粉圓。', '甜度和冰塊可以依自己的喜好選擇。', '現在風靡全世界,成為代表台灣的飲料。'],
      jk: [['でんぷん', '', '澱粉'], ['もちもち', '', 'Q 彈'], ['好み', 'このみ', '喜好'], ['代表する', 'だいひょうする', '代表']] },
    { p: 3, q: '澎湖を紹介してください。', zh: '請介紹澎湖。',
      ja: ['澎湖は台湾海峡に浮かぶ約90の島々からなる諸島です。', '柱状の玄武岩や、石を積んで作った伝統的な漁具「石滬」が有名です。', '七美島にあるハート形の「双心石滬」は特に人気があります。', '冬は風がとても強いので、4月から9月ごろがおすすめです。'],
      jz: ['澎湖是由台灣海峽上約 90 座島嶼組成的群島。', '柱狀玄武岩,以及用石頭堆成的傳統漁具「石滬」很有名。', '七美島上心形的「雙心石滬」特別受歡迎。', '冬天風非常大,建議 4 到 9 月左右前往。'],
      jk: [['諸島', 'しょとう', '群島'], ['玄武岩', 'げんぶがん', '玄武岩'], ['漁具', 'ぎょぐ', '漁具'], ['おすすめ', '', '推薦']] }
  ]
};
if (typeof window !== 'undefined') window.ORALMOCK = ORALMOCK;
