/* 口試模擬題庫 · C10 v126
   依「115 年導遊人員及領隊人員評量測驗簡章」外語導遊口試:每人約 10–12 分鐘,
   題目包括「自我介紹」「本國文化與國情」「風景、節慶與美食」三大部分(p = 1 / 2 / 3)。
   en:英語題目 + 參考回答(sample)+ 關鍵字(kw:[英文, 中文]);內容為練習用自編範例,非官方題目。
   jp:日語題目,參考回答與關鍵字沿用 oral_jp.js 的口試主題範例(ref = ORALJP.topics 的索引)。 */
const ORALMOCK = {
  parts: { 1: '自我介紹', 2: '本國文化與國情', 3: '風景、節慶與美食' },
  en: [
    { p: 1, q: 'Please introduce yourself and tell us why you want to be a tour guide.', zh: '請自我介紹,並說明想當導遊的原因。',
      sample: ['Good morning. My name is Lin, and I am from Taichung.', 'I majored in English at university and have worked in hospitality for three years.', 'I love meeting people from different countries and sharing stories about Taiwan.', 'I hope to become a tour guide who makes every visitor feel welcome and safe.'],
      kw: [['major in', '主修'], ['hospitality', '接待服務業'], ['be passionate about', '熱愛'], ['make visitors feel welcome', '讓旅客賓至如歸']] },
    { p: 2, q: 'Could you give a brief introduction to Taiwan?', zh: '請簡單介紹台灣。',
      sample: ['Taiwan is an island in East Asia with a population of about 23 million.', 'It is known for its high mountains, hot springs and beautiful coastline.', 'Taipei is the capital, and Mandarin and Taiwanese are widely spoken.', 'Visitors love Taiwan for its friendly people, convenient transportation and delicious food.'],
      kw: [['population', '人口'], ['mountainous', '多山的'], ['coastline', '海岸線'], ['convenient', '方便的']] },
    { p: 2, q: "Tell us about Taiwan's indigenous peoples.", zh: '請介紹台灣的原住民族。',
      sample: ['Taiwan has 16 officially recognized indigenous peoples.', 'The Amis are the largest group, living mainly on the east coast.', 'Each group has its own language, festivals and traditional clothing.', 'Visitors can learn about their culture at harvest festivals and cultural parks.'],
      kw: [['indigenous peoples', '原住民族'], ['officially recognized', '官方認定'], ['Amis', '阿美族'], ['harvest festival', '豐年祭']] },
    { p: 2, q: 'How can visitors travel around Taiwan?', zh: '旅客在台灣可以怎麼移動?',
      sample: ["Taiwan's High Speed Rail connects Taipei and Kaohsiung in about 90 minutes.", 'In the cities, the MRT is fast, clean and easy to use.', 'An EasyCard can be used on the MRT, on buses and even in convenience stores.', 'For the east coast, trains and tour buses are good choices.'],
      kw: [['High Speed Rail', '高鐵'], ['MRT', '捷運'], ['EasyCard', '悠遊卡'], ['convenience store', '便利商店']] },
    { p: 2, q: 'Tell us about religion and temple culture in Taiwan.', zh: '請介紹台灣的宗教與廟宇文化。',
      sample: ['Many people in Taiwan follow a mix of Buddhism, Taoism and folk beliefs.', 'Temples are community centers, and Mazu, the goddess of the sea, is widely worshipped.', 'During the Mazu pilgrimage, thousands of followers walk for days with the goddess.', 'When visiting a temple, please be quiet and respectful, and ask before taking photos.'],
      kw: [['temple', '廟宇'], ['folk beliefs', '民間信仰'], ['Mazu pilgrimage', '媽祖遶境'], ['incense', '香']] },
    { p: 3, q: 'Please introduce Taipei 101 to a group of visitors.', zh: '請向旅客介紹台北 101。',
      sample: ['Taipei 101 is a 508-meter skyscraper in the Xinyi District of Taipei.', 'It was the tallest building in the world from 2004 to 2010.', 'Its design looks like a stalk of bamboo, a symbol of growth.', 'Inside, a huge tuned mass damper keeps the tower steady during typhoons and earthquakes.'],
      kw: [['skyscraper', '摩天大樓'], ['observatory', '觀景台'], ['tuned mass damper', '風阻尼器'], ["New Year's Eve fireworks", '跨年煙火']] },
    { p: 3, q: 'What would you tell visitors about the National Palace Museum?', zh: '你會怎麼向旅客介紹國立故宮博物院?',
      sample: ["The National Palace Museum in Taipei houses one of the world's largest collections of Chinese art.", 'Its collection has nearly 700,000 pieces spanning thousands of years.', 'The most famous items include the Jadeite Cabbage and the Meat-shaped Stone.', 'I suggest visiting early in the morning to avoid the crowds.'],
      kw: [['collection', '典藏'], ['artifact', '文物'], ['Jadeite Cabbage', '翠玉白菜'], ['Meat-shaped Stone', '肉形石']] },
    { p: 3, q: 'Please introduce Jiufen.', zh: '請介紹九份。',
      sample: ['Jiufen is a mountain town in New Taipei City that grew rich from gold mining.', 'Its narrow old streets are full of teahouses, red lanterns and snack shops.', 'From the town you can enjoy a great view of the sea and the mountains.', 'Many visitors love its nostalgic atmosphere, especially in the evening when the lanterns are lit.'],
      kw: [['gold mining', '採金'], ['old street', '老街'], ['teahouse', '茶樓'], ['nostalgic', '懷舊的']] },
    { p: 3, q: 'Introduce Sun Moon Lake to your tour group.', zh: '請向團員介紹日月潭。',
      sample: ['Sun Moon Lake is the largest lake in Taiwan, located in Nantou County.', 'Its name comes from its shape: one part looks like the sun and the other like the moon.', 'Visitors can take a boat ride, ride a bike along the lake or take the cable car.', "It is also home to the Thao people, one of Taiwan's indigenous groups."],
      kw: [['lake', '湖泊'], ['cable car', '纜車'], ['cycling path', '自行車道'], ['Thao people', '邵族']] },
    { p: 3, q: 'What can visitors see at Alishan?', zh: '旅客在阿里山可以看到什麼?',
      sample: ['Alishan is a famous mountain area in Chiayi County.', 'It is well known for the sunrise, the sea of clouds and the giant sacred trees.', 'Visitors can ride the Alishan Forest Railway, a famous mountain railway.', 'In spring, the cherry blossoms make Alishan even more beautiful.'],
      kw: [['sunrise', '日出'], ['sea of clouds', '雲海'], ['sacred tree', '神木'], ['forest railway', '森林鐵路']] },
    { p: 3, q: 'Please introduce Taroko National Park.', zh: '請介紹太魯閣國家公園。',
      sample: ['Taroko National Park is in Hualien on the east coast of Taiwan.', 'The Taroko Gorge was cut by the Liwu River through marble cliffs.', 'Popular spots include the Swallow Grotto and the Eternal Spring Shrine.', 'Please check the trail conditions before visiting, because some trails may close after earthquakes or heavy rain.'],
      kw: [['gorge', '峽谷'], ['marble', '大理石'], ['Swallow Grotto', '燕子口'], ['Eternal Spring Shrine', '長春祠']] },
    { p: 3, q: 'Why are night markets so popular in Taiwan?', zh: '為什麼夜市在台灣這麼受歡迎?',
      sample: ['Night markets are an important part of daily life in Taiwan.', 'Shilin Night Market in Taipei is one of the most famous.', 'You can try local snacks like stinky tofu, oyster omelets and bubble tea.', "There are also games and inexpensive clothes, so it's fun for everyone."],
      kw: [['street food', '街頭小吃'], ['stinky tofu', '臭豆腐'], ['oyster omelet', '蚵仔煎'], ['bargain', '殺價']] },
    { p: 3, q: 'Recommend some Taiwanese dishes to foreign visitors.', zh: '請向外國旅客推薦台灣料理。',
      sample: ["Beef noodle soup is one of Taiwan's most famous dishes.", 'Xiaolongbao, or soup dumplings, are very popular with visitors.', 'Braised pork rice is a simple but delicious local favorite.', 'For dessert, try mango shaved ice or a cup of bubble milk tea.'],
      kw: [['beef noodle soup', '牛肉麵'], ['soup dumplings', '小籠包'], ['braised pork rice', '滷肉飯'], ['shaved ice', '剉冰']] },
    { p: 3, q: 'Please introduce a traditional festival in Taiwan.', zh: '請介紹一個台灣的傳統節慶。',
      sample: ['The Lantern Festival is on the 15th day of the first lunar month.', 'In Pingxi, people write their wishes on sky lanterns and release them into the night sky.', 'In Yanshui, people enjoy the exciting beehive fireworks.', 'Other important festivals include the Dragon Boat Festival and the Mid-Autumn Festival.'],
      kw: [['lunar calendar', '農曆'], ['sky lantern', '天燈'], ['beehive fireworks', '鹽水蜂炮'], ['Dragon Boat Festival', '端午節']] },
    { p: 3, q: 'Introduce Beitou Hot Springs to visitors.', zh: '請向旅客介紹北投溫泉。',
      sample: ['Beitou is a hot spring area in northern Taipei that is easy to reach by MRT.', 'Its hot spring culture began during the Japanese colonial period.', 'Visitors can see the Thermal Valley and the Beitou Hot Spring Museum.', 'Remember to wash before entering a public bath and to drink enough water.'],
      kw: [['hot spring', '溫泉'], ['Thermal Valley', '地熱谷'], ['colonial period', '殖民時期'], ['public bath', '公共浴池']] },
    { p: 3, q: 'What souvenirs would you recommend from Taiwan?', zh: '你會推薦哪些台灣伴手禮?',
      sample: ['Pineapple cakes are the most popular souvenir from Taiwan.', 'High-mountain oolong tea is another great choice.', 'Some visitors like nougat candy or dried mango.', 'You can buy them at bakeries, tea shops or the airport.'],
      kw: [['pineapple cake', '鳳梨酥'], ['oolong tea', '烏龍茶'], ['nougat', '牛軋糖'], ['dried mango', '芒果乾']] }
  ],
  jp: [
    { p: 1, q: '自己紹介をしてください。ガイドを目指す理由も教えてください。', zh: '請自我介紹,並說明想當導遊的原因。', ref: 0 },
    { p: 2, q: '台湾について簡単に紹介してください。', zh: '請簡單介紹台灣。', ref: 1 },
    { p: 2, q: '台湾の原住民族について説明してください。', zh: '請介紹台灣的原住民族。', ref: 12 },
    { p: 2, q: '台湾国内の移動手段を教えてください。', zh: '請介紹在台灣移動的交通方式。', ref: 13 },
    { p: 3, q: '台北101を日本のお客様に紹介してください。', zh: '請向日本旅客介紹台北 101。', ref: 2 },
    { p: 3, q: '国立故宮博物院の見どころを教えてください。', zh: '請介紹國立故宮博物院的看點。', ref: 3 },
    { p: 3, q: '九份を紹介してください。', zh: '請介紹九份。', ref: 4 },
    { p: 3, q: '日月潭の魅力を説明してください。', zh: '請說明日月潭的魅力。', ref: 5 },
    { p: 3, q: '阿里山ではどんな景色が楽しめますか。', zh: '在阿里山可以欣賞到什麼景色?', ref: 6 },
    { p: 3, q: '太魯閣国家公園を紹介してください。', zh: '請介紹太魯閣國家公園。', ref: 7 },
    { p: 3, q: '台湾の夜市について紹介してください。', zh: '請介紹台灣的夜市。', ref: 8 },
    { p: 3, q: '日本のお客様におすすめの台湾料理を紹介してください。', zh: '請向日本旅客推薦台灣料理。', ref: 9 },
    { p: 3, q: '台湾の伝統的なお祭りを一つ紹介してください。', zh: '請介紹一個台灣的傳統節慶。', ref: 10 },
    { p: 3, q: '北投温泉を紹介してください。', zh: '請介紹北投溫泉。', ref: 11 },
    { p: 3, q: '台湾のおすすめのお土産を教えてください。', zh: '請推薦台灣的伴手禮。', ref: 14 }
  ]
};
if (typeof window !== 'undefined') window.ORALMOCK = ORALMOCK;
